CREATE TABLE [dbo].[ApprovedQualificationsImport]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[DateOfOfqualDataSnapshot]													DATETIME		NULL,
	[QualificationName]															NVARCHAR(255)	NULL,
	[AwardingOrganisation]														NVARCHAR(255)	NULL,
	[QualificationNumber] FLOAT NULL,
	[Level] NVARCHAR(255) NULL,
	[QualificationType] NVARCHAR(255) NULL,
	[Subcategory] NVARCHAR(255) NULL,
	[SectorSubjectArea] NVARCHAR(255) NULL,
	[Status] NVARCHAR(255) NULL,
	[Age1416_FundingAvailable] [bit] NOT NULL,
	[Age1416_FundingApprovalStartDate] NVARCHAR(255) NULL,
	[Age1416_FundingApprovalEndDate] NVARCHAR(255) NULL,
	[Age1416_Notes] NVARCHAR(255) NULL,
	[Age1619_FundingAvailable] [bit] NOT NULL,
	[Age1619_FundingApprovalStartDate] [datetime] NULL,
	[Age1619_FundingApprovalEndDate] [datetime] NULL,
	[Age1619_Notes] NVARCHAR(255) NULL,
	[LocalFlexibilities_FundingAvailable] [bit] NOT NULL,
	[LocalFlexibilities_FundingApprovalStartDate] [datetime] NULL,
	[LocalFlexibilities_FundingApprovalEndDate] [datetime] NULL,
	[LocalFlexibilities_Notes] NVARCHAR(255) NULL,
	[LegalEntitlementL2L3_FundingAvailable] [bit] NOT NULL,
	[LegalEntitlementL2L3_FundingApprovalStartDate] NVARCHAR(255) NULL,
	[LegalEntitlementL2L3_FundingApprovalEndDate] NVARCHAR(255) NULL,
	[LegalEntitlementL2L3_Notes] NVARCHAR(255) NULL,
	[LegalEntitlementEnglishandMaths_FundingAvailable] [bit] NOT NULL,
	[LegalEntitlementEnglishandMaths_FundingApprovalStartDate] NVARCHAR(255) NULL,
	[LegalEntitlementEnglishandMaths_FundingApprovalEndDate] NVARCHAR(255) NULL,
	[LegalEntitlementEnglishandMaths_Notes] NVARCHAR(255) NULL,
	[DigitalEntitlement_FundingAvailable] [bit] NOT NULL,
	[DigitalEntitlement_FundingApprovalStartDate] NVARCHAR(255) NULL,
	[DigitalEntitlement_FundingApprovalEndDate] NVARCHAR(255) NULL,
	[DigitalEntitlement_Notes] NVARCHAR(255) NULL,
	[ESFLevel34_FundingAvailable] [bit] NOT NULL,
	[ESFLevel34_FundingApprovalStartDate] NVARCHAR(255) NULL,
	[ESFLevel34_FundingApprovalEndDate] NVARCHAR(255) NULL,
	[ESFLevel34_Notes] NVARCHAR(255) NULL,
	[AdvancedLearnerLoans_FundingAvailable] [bit] NOT NULL,
	[AdvancedLearnerLoans_FundingApprovalStartDate] NVARCHAR(255) NULL,
	[AdvancedLearnerLoans_FundingApprovalEndDate] NVARCHAR(255) NULL,
	[AdvancedLearnerLoans_Notes] NVARCHAR(255) NULL,
	[AwardingOrganisationURL] NVARCHAR(255) NULL,
	[L3FreeCoursesForJobs_FundingAvailable] [bit] NOT NULL,
	[L3FreeCoursesForJobs_FundingApprovalStartDate] NVARCHAR(255) NULL,
	[L3FreeCoursesForJobs_FundingApprovalEndDate] NVARCHAR(255) NULL,
	[L3FreeCoursesForJobs_Notes] NVARCHAR(255) NULL,
	[QualificationNumberVarchar] [varchar](100) NULL
)
