CREATE TABLE [dbo].[RegisteredQualificationsImport]
(
	[Id]                                    INT IDENTITY (1, 1)            NOT NULL,
	[QualificationNumber]                   VARCHAR(10)                    NOT NULL,
	[QualificationNumberNoObliques]         VARCHAR(50)                    NOT NULL,
	[Title]                                 VARCHAR(250)                   NOT NULL,
	[Status]                                VARCHAR(100)                   NOT NULL,
	[OrganisationName]                      VARCHAR(250)                   NOT NULL,
	[OrganisationAcronym]                   VARCHAR(50)                    NOT NULL,
	[OrganisationRecognitionNumber]         VARCHAR(10)                    NOT NULL,
	[Type]                                  VARCHAR(50)                    NOT NULL,
	[Ssa]                                   VARCHAR(150)                   NOT NULL,
	[Level]                                 VARCHAR(50)                    NOT NULL,
	[SubLevel]                              VARCHAR(50)                    NOT NULL,
	[EqfLevel]                              VARCHAR(50)                    NOT NULL,
	[GradingType]                           VARCHAR(50),
	[GradingScale]                          VARCHAR(250),
	[TotalCredits]                          INTEGER,
	[Tqt]                                   INTEGER,
	[Glh]                                   INTEGER,
	[MinimumGLH]                            INTEGER,
	[MaximumGLH]                            INTEGER,
	[RegulationStartDate]                   DATETIME                       NOT NULL,
	[OperationalStartDate]                  DATETIME                       NOT NULL,
	[OperationalEndDate]                    DATETIME,
	[CertificationEndDate]                  DATETIME,
	[ReviewDate]                            DATETIME,
	[OfferedInEngland]                      BIT                            NOT NULL,
	[OfferedInNorthernIreland]              BIT                            NOT NULL,
	[OfferedInternationally]                BIT,
	[Specialism]                            VARCHAR(MAX),
	[Pathways]                              VARCHAR(MAX),
	[AssessmentMethods]                     VARCHAR(MAX),
	[ApprovedForDELFundedProgramme]         VARCHAR(150),
	[LinkToSpecification]                   VARCHAR(MAX),
	[ApprenticeshipStandardReferenceNumber] VARCHAR(50),
	[ApprenticeshipStandardTitle]           VARCHAR(150),
	[RegulatedByNorthernIreland]            BIT                            NOT NULL,
	[NiDiscountCode]                        VARCHAR(150),
	[GceSizeEquivalence]                    VARCHAR(50),
	[GcseSizeEquivalence]                   VARCHAR(50),
	[EntitlementFrameworkDesignation]       VARCHAR(50),
	[LastUpdatedDate]                       DATETIME                       NOT NULL,
	[UiLastUpdatedDate]                     DATETIME                       NOT NULL,
    [InsertedDate]							DATETIME                       NOT NULL,
    [Version]								INTEGER,
    [AppearsOnPublicRegister]				BIT,
    [OrganisationId]						INTEGER,
    [LevelId]								INTEGER,
    [TypeId]								INTEGER,
    [SsaId]									INTEGER,
    [GradingTypeId]							INTEGER,
    [GradingScaleId]						INTEGER,
    [PreSixteen]							BIT,
    [SixteenToEighteen]						BIT,
    [EighteenPlus]							BIT,
    [NineteenPlus]							BIT,
	[ImportStatus]							VARCHAR(50)                    DEFAULT 'New',
	[ChangedFields]							VARCHAR(MAX),				
	
	CONSTRAINT [PK_RegisteredQualification] PRIMARY KEY CLUSTERED ([Id] ASC),
)
