CREATE TABLE [dbo].[RegisteredQualificationsImport]
(
	[Id]                                    INT IDENTITY (1, 1)            NOT NULL,
	[QualificationNumber]                   VARCHAR(10)                    NOT NULL,
	[QualificationNumberNoObliques]         VARCHAR(50)                    NOT NULL,
	[Title]                                 VARCHAR(250)                   NOT NULL,
	[Status]                                VARCHAR(17)                    NOT NULL,
	[OrganisationName]                      VARCHAR(250)                    NOT NULL,
	[OrganisationAcronym]                   VARCHAR(25)                     NOT NULL,
	[OrganisationRecognitionNumber]         VARCHAR(6)                     NOT NULL,
	[Type]                                  VARCHAR(41)                    NOT NULL,
	[Ssa]                                   VARCHAR(150)                   NOT NULL,
	[Level]                                 VARCHAR(25)                    NOT NULL,
	[SubLevel]                              VARCHAR(4)                     NOT NULL,
	[EqfLevel]                              VARCHAR(25)                    NOT NULL,
	[GradingType]                           VARCHAR(30),
	[GradingScale]                          VARCHAR(30),
	[TotalCredits]                          INTEGER                        NOT NULL,
	[Tqt]                                   INTEGER,
	[Glh]                                   INTEGER,
	[MinimumGLH]                            INTEGER                        NOT NULL,
	[MaximumGLH]                            INTEGER                        NOT NULL,
	[RegulationStartDate]                   DATETIME                       NOT NULL,
	[OperationalStartDate]                  DATETIME                       NOT NULL,
	[OperationalEndDate]                    DATETIME                       NOT NULL,
	[CertificationEndDate]                  DATETIME                       NOT NULL,
	[ReviewDate]                            DATETIME                       NOT NULL,
	[OfferedInEngland]                      BIT                            NOT NULL,
	[OfferedInNorthernIreland]              BIT                            NOT NULL,
	[OfferedInternationally]                BIT,
	[Specialism]                            VARCHAR(30),
	[Pathways]                              VARCHAR(30),
	[AssessmentMethods]                     VARCHAR(250),
	[ApprovedForDELFundedProgramme]         VARCHAR(30),
	[LinkToSpecification]                   VARCHAR(250),
	[ApprenticeshipStandardReferenceNumber] VARCHAR(30),
	[ApprenticeshipStandardTitle]           VARCHAR(30),
	[RegulatedByNorthernIreland]            BIT                            NOT NULL,
	[NiDiscountCode]                        VARCHAR(30),
	[GceSizeEquivalence]                    VARCHAR(30),
	[GcseSizeEquivalence]                   VARCHAR(30),
	[EntitlementFrameworkDesignation]       VARCHAR(30),
	[LastUpdatedDate]                       DATETIME                       NOT NULL,
	[UiLastUpdatedDate]                     DATETIME                       NOT NULL,
    [InsertedDate]							DATETIME                       NOT NULL,
    [Version]								INTEGER,
    [AppearsOnPublicRegister]				BIT,
    [OrganisationId]						INTEGER,
    [LevelId]								INTEGER,
    [TypeId]								INTEGER,
    [SsaId]									INTEGER,
    [GradingTypeId]							INTEGER,
    [GradingScaleId]						INTEGER,
    [PreSixteen]							BIT,
    [SixteenToEighteen]						BIT,
    [EighteenPlus]							BIT,
    [NineteenPlus]							BIT,
	[ImportStatus]							VARCHAR(50)                    DEFAULT 'New',
	
	CONSTRAINT [PK_RegisteredQualification] PRIMARY KEY CLUSTERED ([Id] ASC),
)
